logging:
  file: logs/proxy_server.log
  level:
    root: DEBUG
spring:
  data:
    mongodb:
      uri: mongodb://mongodb-1:27017/proxy
server:
  port: 9090
proxyServer:
  maximumResponseBufferSize: 1073741824
  SSLEnabled: true
  port: 9080
  rootCertificatePath: /data/proxy/file/certificate.cer
  privateKeyPath: /data/proxy/file/private-key.pem
  rootCertificateAndKeyPath: /data/proxy/file/keystore.p12
  passwordForPrivateKey: 1q2w3e4r
  keyStoreType: PKCS12
  privateKeyAlias: ProxyServerPrivateKey
proxyCache:
  cachePath: /data/proxy/cache
  fileTypes:
    - .apk
    - .ipa
    - .zip
    - .gz
    - .tar
    - .rar
    - .7z
    - .jar
    - .exe